AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mobile-dfs-lineup-builder

  Sample SAM Template for mobile-dfs-lineup-builder

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  WriteSlateDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Policies:
      DynamoDBWritePolicy:
        TableName: !Ref DynamoDBTable
    Properties:
      CodeUri: GetSlateDataFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

  SlateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dfs-lineup-builder-slate
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: SlateId
          AttributeType: S
        - AttributeName: StartDate
          AttributeType: S
      KeySchema:
        - AttributeName: SlateId
          KeyType: HASH
        - AttributeName: StartDate
          KeyType: RANGE
