AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mobile-dfs-lineup-builder

  Sample SAM Template for mobile-dfs-lineup-builder

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  WriteSlateDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: GetSlateDataFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref SlateTable
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 * * ? *)

  SlateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dfs-lineup-builder-slate
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: SlateId
          AttributeType: S
        - AttributeName: StartDate
          AttributeType: S
      KeySchema:
        - AttributeName: SlateId
          KeyType: HASH
        - AttributeName: StartDate
          KeyType: RANGE

  GetRegulationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: GetRegulationsFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref RegulationTable
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)

  RegulationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dfs-lineup-builder-regulations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: StateName
          AttributeType: S
      KeySchema:
        - AttributeName: StateName
          KeyType: HASH

  QueryRegulationDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: QueryRegulationDataFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref RegulationTable
      Events:
        QuerySlateDataEvent:
          Type: Api
          Properties:
            Path: /getregulations
            Method: GET
            RestApiId:
              Ref: QueryRegulationDataApi

  QueryRegulationDataApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: QueryRegulationDataApi
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: DAY
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dfs-lineup-builder-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: N
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH

  QueryUserLineupDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: QueryUserLineupDataFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref LineupTable
      Events:
        QuerySlateDataEvent:
          Type: Api
          Properties:
            Path: /getuserlineup
            Method: GET
            RestApiId:
              Ref: QueryUserLineupDataApi

  QueryUserLineupDataApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name:  QueryUserLineupDataApi
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: DAY

  QuerySlateDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: QuerySlateDataFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref SlateTable
      Events:
        QuerySlateDataEvent:
          Type: Api
          Properties:
            Path: /getslates
            Method: GET
            RestApiId:
              Ref: QuerySlateDataApi

  QuerySlateDataApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: QuerySlateDataApi
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: DAY

  WriteLineupsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: WriteLineupsFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref LineupTable
      Events:
        QuerySlateDataEvent:
          Type: Api
          Properties:
            Path: /writelineup
            Method: POST
            RestApiId:
              Ref: WriteLineupApi

  WriteLineupApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: WriteLineupApi
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: DAY

  LineupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dfs-lineup-builder-lineups
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LineupId
          AttributeType: N
        - AttributeName: UserId
          AttributeType: N
      KeySchema:
        - AttributeName: LineupId
          KeyType: HASH
        - AttributeName: UserId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi-userid
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  WriteUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: WriteUserFunction
      Handler: slate.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref UserTable
      Events:
        QuerySlateDataEvent:
          Type: Api
          Properties:
            Path: /writeuser
            Method: POST
            RestApiId:
              Ref: WriteUserApi

  WriteUserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: WriteUserApi
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: DAY

